### ISSUE TITLE
Portfolio dependency

### ISSUE THREAD

**Issue by stefk** [iCAPLyon1/BadgeBundle#13]
The v6/master branch of this bundle has an undeclared dependency on `icap/porfolio-bundle`. On fresh installs, this causes fatal errors if the the portfolio bundle is missing.

**Comment by maxailloud** [comment]
Can you give me the errors it displayed?

**Comment by stefk** [comment]
I don't have the exact message anymore, but it was a "Class not found" fatal error coming from [this file](https://github.com/iCAPLyon1/BadgeBundle/blob/master/Form/Type/Portfolio/BadgesType.php), on `AbstractWidgetType`, if I remember correctly.

**Comment by maxailloud** [comment]
I will give a look.

**Comment by maxailloud** [comment]
Did you had the issue during the installation process or when using the platform?

**Comment by stefk** [comment]
I just updated my composer.json with v6 versions of available plugins, and launched composer. I think the error happened at the end, when building the cache. You should be able to reproduce it by disabling the portfolio bundle in bundles.ini, removing the cache, and executing any command.

**Comment by maxailloud** [comment]
I didn't succeed to reproduce so I'm installing a new platform to see if I can get the error.

**Comment by stefk** [comment]
@maxailloud, here's the error:

> PHP Fatal error:  Class 'Icap\BadgeBundle\Form\Type\Portfolio\AbstractWidgetType' not found in /home/skl@ecam.be/projets/claronext/vendor/icap/badge-bundle/Icap/BadgeBundle/Form/Type/Portfolio/BadgesType.php on line 16

You probably had to remove the porfolio bundle from _vendor/composer/autoload_namespaces.php_ as well.

**Comment by maxailloud** [comment]
This is weird as in my code the class AbstractWidgetType is imported from Icap\PortfolioBundle\Form\Type\Widgets\AbstractWidgetType. It should have said that the class Icap\PortfolioBundle\Form\Type\Widgets\AbstractWidgetType is not found.

Even removing the portfolio bundle from vendor/composer/autoload_namespaces.php I didn't get the error. I'll try to remove the portfolio bundle at all.

**Comment by stefk** [comment]
Correction, the error is:

> Class 'Icap\PortfolioBundle\Form\Type\Widgets\AbstractWidgetType' not found in /home/skl@ecam.be/projets/claronext/vendor/icap/badge-bundle/Icap/BadgeBundle/Form/Type/Portfolio/BadgesType.php

(previous error was due to a missing `use` statement, don't know how it happened...)

**Comment by maxailloud** [comment]
Ok it seems more logical so.

**Comment by maxailloud** [comment]
I now have the error. I think my PHP was broken because I had to reboot to get an error from it^^

I will try to make a patch so.

**Comment by stefk** [comment]
Thanks.
